#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  1 13:15:30 2021

@author: liushiwei
"""

import tkinter as tk

win = tk.Tk()
win.title('計算機')

f1 = tk.Frame(win)
f1.pack(fill = 'x')
f2 = tk.Frame(win)
f2.pack()


def _btn1():
    entry1.insert('end', '1')

def _btn2():
    entry1.insert('end', '2')
    
def _btn3():
    entry1.insert('end', '3')
    
def _btn4():
    entry1.insert('end', '+')

def _btn5():
    entry1.insert('end', '4')
    
def _btn6():
    entry1.insert('end', '5')
    
def _btn7():
    entry1.insert('end', '6')
    
def _btn8():
    entry1.insert('end', '-')
    
def _btn9():
    entry1.insert('end', '7')
    
def _btn10():
    entry1.insert('end', '8')
    
def _btn11():
    entry1.insert('end', '9')
    
def _btn12():
    entry1.insert('end', '*')
    
def _btn13():
    entry1.insert('end', '0')
    
def _btn14():
    entry1.delete(0, 'end')
    labelVar.set('計算結果')
    
def _btn15():
    entry1.insert('end', '=')
    
def _btn16():
    entry1.insert('end', '/')
    
def compute_btn():
    var = entry1.get()
    if '+' in var:
        data = var.split('+')
        labelVar.set(eval(data[0]) + eval(data[1]))
    elif '-' in var:
        data = var.split('-')
        labelVar.set(eval(data[0]) - eval(data[1]))
    elif '*' in var:
        data = var.split('*')
        labelVar.set(eval(data[0]) * eval(data[1]))
    else:
        data = var.split('/')
        labelVar.set(round(eval(data[0]) / eval(data[1]),2))


entry1 = tk.Entry(f1 ,justify = 'center')
entry1.pack()
labelVar = tk.StringVar()
labelVar.set('計算結果')
label1 = tk.Label(f1, textvariable = labelVar, bg = 'yellow', fg = 'red')
label1.pack(fill = 'x')

btn1 = tk.Button(f2, text = '1', command = _btn1)
btn2 = tk.Button(f2, text = '2', command = _btn2)
btn3 = tk.Button(f2, text = '3', command = _btn3)
btn4 = tk.Button(f2, text = '+', command = _btn4)
btn5 = tk.Button(f2, text = '4', command = _btn5)
btn6 = tk.Button(f2, text = '5', command = _btn6)
btn7 = tk.Button(f2, text = '6', command = _btn7)
btn8 = tk.Button(f2, text = '-', command = _btn8)
btn9 = tk.Button(f2, text = '7', command = _btn9)
btn10 = tk.Button(f2, text = '8', command = _btn10)
btn11 = tk.Button(f2, text = '9', command = _btn11)
btn12 = tk.Button(f2, text = '*', command = _btn12)
btn13 = tk.Button(f2, text = '0', command = _btn13)
btn14 = tk.Button(f2, text = 'cls', command = _btn14)
btn15 = tk.Button(f2, text = '=', command = compute_btn)
btn16 = tk.Button(f2, text = '/', command = _btn16)

btn1.grid(row = 0, column = 0)
btn2.grid(row = 0, column = 1)
btn3.grid(row = 0, column = 2)
btn4.grid(row = 0, column = 3)
btn5.grid(row = 1, column = 0)
btn6.grid(row = 1, column = 1)
btn7.grid(row = 1, column = 2)
btn8.grid(row = 1, column = 3)
btn9.grid(row = 2, column = 0)
btn10.grid(row = 2, column = 1)
btn11.grid(row = 2, column = 2)
btn12.grid(row = 2, column = 3)
btn13.grid(row = 3, column = 0)
btn14.grid(row = 3, column = 1)
btn15.grid(row = 3, column = 2)
btn16.grid(row = 3, column = 3)



win.mainloop()
